services:
  - type: web
    name: livingstonepharmacy-admin
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://livingstonepharmacy-admin.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: livingstonepharmacy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: livingstonepharmacy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: livingstonepharmacy-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: livingstonepharmacy-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: livingstonepharmacy-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug

databases:
  - name: livingstonepharmacy-db
    databaseName: livingstonepharmacy
    user: livingstonepharmacy_user
